<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use App\Models\Tasktype;
use App\Models\Subtask;

class TasktypeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
      $tasktypes = array(
        'core-cabl-bdf1-',
        'core-cabl-bdf2-',
        'core-cabl-mpo1-',
        'core-cabl-mp02-',
        'core-infra-bdf1-',
        'core-infra-bdf2-',
        'core-infra-mpo1-',
        'core-infra-mpo2-',
        'core-netw-bdf1-',
        'core-netw-bdf2-',
        'core-netw-mpo1-',
        'core-netw-mpo2-',
        'dha-cabl-dha-',
        'dha-cabl-mdfa-',
        'dha-infra-dhb-',
        'dha-infra-mdfb',
        'dha-netw-dhb-',
        'dha-netw-mdfb',
        'dhb-cabl-dhb-',
        'dhb-cabl-mdfb',
        'dhb-infra-dhb',
        'dhb-infra-mdfb-',
        'dhb-netw-dhb-',
        'dhb-netw-mdfb-',
        'dhc-cabl-dhc-',
        'dhc-cabl-mdfc-',
        'dhc-infra-dhc-',
        'dhc-infra-mdfc-',
        'dhc-netw-dhc-',
        'dhc-netw-mdfc-',
        'dhd-cabl-dhc-',
        'dhd-cabl-mdfc-',
        'dhd-infra-dhc-',
        'dhd-infra-mdfc-',
        'dhd-netw-dhc-',
        'dhd-netw-mdfc-',
        'eqprent-misc-cons-',
        'eqprent-misc-eqip-',
        'eqprent-unbill-eqip-',
        'freight-misc-frgt-',
        'gs-cabl-adm-',
        'gs-cabl-bdf1-',
        'gs-cabl-bdf2-',
        'gs-cabl-dha-',
        'gs-cabl-dhb-',
        'gs-cabl-dhc-',
        'gs-cabl-dhd-',
        'gs-cabl-era-',
        'gs-cabl-erb-',
        'gs-cabl-erc-',
        'gs-cabl-erd-',
        'gs-cabl-ern1-',
        'gs-cabl-ern2-',
        'gs-cabl-g1m1-',
        'gs-cabl-g1m2-',
        'gs-cabl-g2m1-',
        'gs-cabl-g2m2-',
        'gs-cabl-gdha-',
        'gs-cabl-gdhd-',
        'gs-cabl-gia-',
        'gs-cabl-gib-',
        'gs-cabl-gic-',
        'gs-cabl-gid-',
        'gs-cabl-gph-',
        'gs-cabl-magb-',
        'gs-cabl-mdfa-',
        'gs-cabl-mdfb-',
        'gs-cabl-mdfc-',
        'gs-cabl-mdfd-',
        'gs-cabl-mpo1-',
        'gs-cabl-mpo2-',
        'gs-cabl-msg1-',
        'gs-cabl-msg2-',
        'gs-cabl-msg3-',
        'gs-cabl-msg4-',
        'gs-cabl-msg5-',
        'gs-cabl-msg6-',
        'gs-cabl-msga-',
        'gs-cabl-msgc-',
        'gs-cabl-msgd-',
        'gs-cabl-msge-',
        'gs-infra-adm-',
        'gs-infra-bdf1-',
        'gs-infra-bdf2-',
        'gs-infra-dha-',
        'gs-infra-dhb-',
        'gs-infra-dhc-',
        'gs-infra-dhd-',
        'gs-infra-era-',
        'gs-infra-erb-',
        'gs-infra-erc-',
        'gs-infra-erd-',
        'gs-infra-ern1-',
        'gs-infra-ern2-',
        'gs-infra-g1m1-',
        'gs-infra-g1m2-',
        'gs-infra-g2m1-',
        'gs-infra-g2m2-',
        'gs-infra-gdha-',
        'gs-infra-gdhd-',
        'gs-infra-gia-',
        'gs-infra-gib-',
        'gs-infra-gic-',
        'gs-infra-gid-',
        'gs-infra-gph-',
        'gs-infra-magb-',
        'gs-infra-mdfa-',
        'gs-infra-mdfb-',
        'gs-infra-mdfc-',
        'gs-infra-mdfd-',
        'gs-infra-mpo1-',
        'gs-infra-mpo2-',
        'gs-infra-msg1-',
        'gs-infra-msg2-',
        'gs-infra-msg3-',
        'gs-infra-msg4-',
        'gs-infra-msg5-',
        'gs-infra-msg6-',
        'gs-infra-msga-',
        'gs-infra-msgc-',
        'gs-infra-msgd-',
        'gs-infra-msge-',
        'gs-netw-adm-',
        'gs-netw-bdf1-',
        'gs-netw-bdf2-',
        'gs-netw-dha-',
        'gs-netw-dhb-',
        'gs-netw-dhc-',
        'gs-netw-dhd-',
        'gs-netw-era-',
        'gs-netw-erb-',
        'gs-netw-erc-',
        'gs-netw-erd-',
        'gs-netw-ern1-',
        'gs-netw-ern2-',
        'gs-netw-g1m1-',
        'gs-netw-g1m2-',
        'gs-netw-g2m1-',
        'gs-netw-g2m2-',
        'gs-netw-gdha-',
        'gs-netw-gdhd-',
        'gs-netw-gia-',
        'gs-netw-gib-',
        'gs-netw-gic-',
        'gs-netw-gid-',
        'gs-netw-gph-',
        'gs-netw-magb-',
        'gs-netw-mdfa-',
        'gs-netw-mdfb-',
        'gs-netw-mdfc-',
        'gs-netw-mdfd-',
        'gs-netw-mpo1-',
        'gs-netw-mpo2-',
        'gs-netw-msg1-',
        'gs-netw-msg2-',
        'gs-netw-msg3-',
        'gs-netw-msg4-',
        'gs-netw-msg5-',
        'gs-netw-msg6-',
        'gs-netw-msga-',
        'gs-netw-msgc-',
        'gs-netw-msgd-',
        'gs-netw-msge-',
        'ind stff-admin-adm-',
        'ind stff-admin-apm-',
        'ind stff-admin-fore-',
        'ind stff-admin-lays-',
        'ind stff-admin-mhan-',
        'ind stff-admin-mman-',
        'ind stff-admin-p6-',
        'ind stff-admin-pe-',
        'ind stff-admin-pm-',
        'ind stff-admin-qa-',
        'ind stff-admin-safm-',
        'ind stff-admin-safp-',
        'ind stff-admin-srpm-',
        'ind stff-admin-stpm-',
        'ind stff-admin-super-',
        'safemeetwarmup-misc-smwu-',
        'sche unproduc-misc-snpt-',
        'train-misc-trne-',
        'train-misc-trnh-',
        'train-unbill-trne-',
        'train-unbill-trnh-',
        'travel-misc-trve-',
        'travel-misc-trvh-',
        'travel-unbill-trvh-',
        'travel-unbill-trvl-',
        'unsche unprod-misc-nsn-',
        'ware-misc-whs-',
      );
      
      foreach($tasktypes as $key=>$value){
        $tasktypeID = DB::table('tasktypes')->insertGetId([
          'name' => $value,
          'description' => ''
        ]);

        $tasktype = Tasktype::findOrFail($tasktypeID);

        $subtasks = Subtask::all()
              ->random(mt_rand(1,16))
              ->pluck('id');

        $tasktype->subtasks()->attach($subtasks);
      }
    }
}
