<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use App\Models\Tasktype;
use App\Models\Subtask;

class TasktypeSeeder extends Seeder
{
      /**
      * Run the database seeds.
      *
      * @return void
      */
      public function run()
      {
            // $tasktypes = array(
            //       'adm' => [],
            //       'apm' => [],
            //       'bdf1' => [],
            //       'bdf2' => [],
            //       'cons' => [],
            //       'dha' => [],
            //       'dhb' => [],
            //       'dhc' => [],
            //       'dhd' => [],
            //       'eqip' => [],
                  
            //       'era' => [],
            //       'erb' => [],
            //       'erc' => [],
            //       'erd' => [],
            //       'ern1' => [],
            //       'ern2' => [],
            //       'fore' => [],
            //       'frgt' => [],
            //       'g1m1' => [],
            //       'g1m2' => [],
                  
            //       'g2m1' => [],
            //       'g2m2' => [],
            //       'gdha' => [],
            //       'gdhd' => [],
            //       'gia' => [],
            //       'gib' => [],
            //       'gic' => [],
            //       'gid' => [],
            //       'gph' => [],
            //       'lays' => [],
                  
            //       'magb' => [],
            //       'mdfa' => [],
            //       'mdfb' => [],
            //       'mdfc' => [],
            //       'mdfd' => [],
            //       'mhan' => [],
            //       'mman' => [],
            //       'mpo1' => [],
            //       'mpo2' => [],
            //       'msg1' => [],
                  
            //       'msg2' => [],
            //       'msg3' => [],
            //       'msg4' => [],
            //       'msg5' => [],
            //       'msg6' => [],
            //       'msga' => [],
            //       'msgc' => [],
            //       'msgd' => [],
            //       'msge' => [],
            //       'nsn' => [],
                  
            //       'p6' => [],
            //       'pe' => [],
            //       'pm' => [],
            //       'qa' => [],
            //       'safm' => [],
            //       'safp' => [],
            //       'smwu' => [],
            //       'snpt' => [],
            //       'srpm' => [],
            //       'stpm' => [],
                  
            //       'super' => [],
            //       'trne' => [],
            //       'trnh' => [],
            //       'trve' => [],
            //       'trvh' => [],
            //       'trvl' => [],
            //       'whs' => [],
            // );
            
            $list_01 = [4,5,6,7,8,9,10,11,26,27,28,29,30,31,47,58,59,60];
            $list_02 = [13,20,21,22,23,24,25,44,49,61,62,63,74];
            $list_03 = [14,16,17,36,37,38,39,40,41,42,50,51];
            $list_04 = [1,2,3,18,32,33,35,43,45,48,53,54,56,57,75];

            $tasktypes = array(
                  'core-cabl-bdf1-' =>                $list_01,
                  'core-cabl-bdf2-' =>                $list_01,
                  'core-cabl-mpo1-' =>                $list_01,
                  'core-cabl-mp02-' =>                $list_01,
                  'core-infra-bdf1-' =>               $list_02,
                  'core-infra-bdf2-' =>               $list_02,
                  'core-infra-mpo1-' =>               $list_02,
                  'core-infra-mpo2-' =>               $list_02,
                  'core-netw-bdf1-' =>                $list_03,
                  'core-netw-bdf2-' =>                $list_03,
                  'core-netw-mpo1-' =>                $list_03,
                  'core-netw-mpo2-' =>                $list_03,
                  'dha-cabl-dha-' =>                  $list_01,
                  'dha-cabl-mdfa-' =>                 $list_01,
                  'dha-infra-dha' =>                  $list_02,
                  'dha-infra-mdfa-' =>                $list_02,
                  'dha-netw-dha-' =>                  $list_03,
                  'dha-netw-mdfa' =>                  $list_03,
                  'dhb-cabl-dhb-' =>                  $list_01,
                  'dhb-cabl-mdfb' =>                  $list_01,
                  'dhb-infra-dhb' =>                  $list_02,
                  'dhb-infra-mdfb-' =>                $list_02,
                  'dhb-netw-dhb-' =>                  $list_03,
                  'dhb-netw-mdfb-' =>                 $list_03,
                  'dhc-cabl-dhc-' =>                  $list_01,
                  'dhc-cabl-mdfc-' =>                 $list_01,
                  'dhc-infra-dhc-' =>                 $list_02,
                  'dhc-infra-mdfc-' =>                $list_02,
                  'dhc-netw-dhc-' =>                  $list_03,
                  'dhc-netw-mdfc-' =>                 $list_03,
                  'dhd-cabl-dhd-' =>                  $list_01,
                  'dhd-cabl-mdfd-' =>                 $list_01,
                  'dhd-infra-dhd-' =>                 $list_02,
                  'dhd-infra-mdfd-' =>                $list_02,
                  'dhd-netw-dhd-' =>                  $list_03,
                  'dhd-netw-mdfd-' =>                 $list_03,
                  'eqprent-misc-cons-' =>             [12],
                  'eqprent-misc-eqip-' =>             [15],
                  'eqprent-unbill-eqip-' =>           [71],
                  'freight-misc-frgt-' =>             [19],
                  'gs-cabl-adm-' =>                   $list_01,
                  'gs-cabl-bdf1-' =>                  $list_01,
                  'gs-cabl-bdf2-' =>                  $list_01,
                  'gs-cabl-dha-' =>                   $list_01,
                  'gs-cabl-dhb-' =>                   $list_01,
                  'gs-cabl-dhc-' =>                   $list_01,
                  'gs-cabl-dhd-' =>                   $list_01,
                  'gs-cabl-era-' =>                   $list_01,
                  'gs-cabl-erb-' =>                   $list_01,
                  'gs-cabl-erc-' =>                   $list_01,
                  'gs-cabl-erd-' =>                   $list_01,
                  'gs-cabl-ern1-' =>                  $list_01,
                  'gs-cabl-ern2-' =>                  $list_01,
                  'gs-cabl-g1m1-' =>                  $list_01,
                  'gs-cabl-g1m2-' =>                  $list_01,
                  'gs-cabl-g2m1-' =>                  $list_01,
                  'gs-cabl-g2m2-' =>                  $list_01,
                  'gs-cabl-gdha-' =>                  $list_01,
                  'gs-cabl-gdhd-' =>                  $list_01,
                  'gs-cabl-gia-' =>                   $list_01,
                  'gs-cabl-gib-' =>                   $list_01,
                  'gs-cabl-gic-' =>                   $list_01,
                  'gs-cabl-gid-' =>                   $list_01,
                  'gs-cabl-gph-' =>                   $list_01,
                  'gs-cabl-magb-' =>                  $list_01,
                  'gs-cabl-mdfa-' =>                  $list_01,
                  'gs-cabl-mdfb-' =>                  $list_01,
                  'gs-cabl-mdfc-' =>                  $list_01,
                  'gs-cabl-mdfd-' =>                  $list_01,
                  'gs-cabl-mpo1-' =>                  $list_01,
                  'gs-cabl-mpo2-' =>                  $list_01,
                  'gs-cabl-msg1-' =>                  $list_01,
                  'gs-cabl-msg2-' =>                  $list_01,
                  'gs-cabl-msg3-' =>                  $list_01,
                  'gs-cabl-msg4-' =>                  $list_01,
                  'gs-cabl-msg5-' =>                  $list_01,
                  'gs-cabl-msg6-' =>                  $list_01,
                  'gs-cabl-msga-' =>                  $list_01,
                  'gs-cabl-msgc-' =>                  $list_01,
                  'gs-cabl-msgd-' =>                  $list_01,
                  'gs-cabl-msge-' =>                  $list_01,
                  'gs-infra-adm-' =>                  $list_02,
                  'gs-infra-bdf1-' =>                 $list_02,
                  'gs-infra-bdf2-' =>                 $list_02,
                  'gs-infra-dha-' =>                  $list_02,
                  'gs-infra-dhb-' =>                  $list_02,
                  'gs-infra-dhc-' =>                  $list_02,
                  'gs-infra-dhd-' =>                  $list_02,
                  'gs-infra-era-' =>                  $list_02,
                  'gs-infra-erb-' =>                  $list_02,
                  'gs-infra-erc-' =>                  $list_02,
                  'gs-infra-erd-' =>                  $list_02,
                  'gs-infra-ern1-' =>                 $list_02,
                  'gs-infra-ern2-' =>                 $list_02,
                  'gs-infra-g1m1-' =>                 $list_02,
                  'gs-infra-g1m2-' =>                 $list_02,
                  'gs-infra-g2m1-' =>                 $list_02,
                  'gs-infra-g2m2-' =>                 $list_02,
                  'gs-infra-gdha-' =>                 $list_02,
                  'gs-infra-gdhd-' =>                 $list_02,
                  'gs-infra-gia-' =>                  $list_02,
                  'gs-infra-gib-' =>                  $list_02,
                  'gs-infra-gic-' =>                  $list_02,
                  'gs-infra-gid-' =>                  $list_02,
                  'gs-infra-gph-' =>                  $list_02,
                  'gs-infra-magb-' =>                 $list_02,
                  'gs-infra-mdfa-' =>                 $list_02,
                  'gs-infra-mdfb-' =>                 $list_02,
                  'gs-infra-mdfc-' =>                 $list_02,
                  'gs-infra-mdfd-' =>                 $list_02,
                  'gs-infra-mpo1-' =>                 $list_02,
                  'gs-infra-mpo2-' =>                 $list_02,
                  'gs-infra-msg1-' =>                 $list_02,
                  'gs-infra-msg2-' =>                 $list_02,
                  'gs-infra-msg3-' =>                 $list_02,
                  'gs-infra-msg4-' =>                 $list_02,
                  'gs-infra-msg5-' =>                 $list_02,
                  'gs-infra-msg6-' =>                 $list_02,
                  'gs-infra-msga-' =>                 $list_02,
                  'gs-infra-msgc-' =>                 $list_02,
                  'gs-infra-msgd-' =>                 $list_02,
                  'gs-infra-msge-' =>                 $list_02,
                  'gs-netw-adm-' =>                   $list_03,
                  'gs-netw-bdf1-' =>                  $list_03,
                  'gs-netw-bdf2-' =>                  $list_03,
                  'gs-netw-dha-' =>                   $list_03,
                  'gs-netw-dhb-' =>                   $list_03,
                  'gs-netw-dhc-' =>                   $list_03,
                  'gs-netw-dhd-' =>                   $list_03,
                  'gs-netw-era-' =>                   $list_03,
                  'gs-netw-erb-' =>                   $list_03,
                  'gs-netw-erc-' =>                   $list_03,
                  'gs-netw-erd-' =>                   $list_03,
                  'gs-netw-ern1-' =>                  $list_03,
                  'gs-netw-ern2-' =>                  $list_03,
                  'gs-netw-g1m1-' =>                  $list_03,
                  'gs-netw-g1m2-' =>                  $list_03,
                  'gs-netw-g2m1-' =>                  $list_03,
                  'gs-netw-g2m2-' =>                  $list_03,
                  'gs-netw-gdha-' =>                  $list_03,
                  'gs-netw-gdhd-' =>                  $list_03,
                  'gs-netw-gia-' =>                   $list_03,
                  'gs-netw-gib-' =>                   $list_03,
                  'gs-netw-gic-' =>                   $list_03,
                  'gs-netw-gid-' =>                   $list_03,
                  'gs-netw-gph-' =>                   $list_03,
                  'gs-netw-magb-' =>                  $list_03,
                  'gs-netw-mdfa-' =>                  $list_03,
                  'gs-netw-mdfb-' =>                  $list_03,
                  'gs-netw-mdfc-' =>                  $list_03,
                  'gs-netw-mdfd-' =>                  $list_03,
                  'gs-netw-mpo1-' =>                  $list_03,
                  'gs-netw-mpo2-' =>                  $list_03,
                  'gs-netw-msg1-' =>                  $list_03,
                  'gs-netw-msg2-' =>                  $list_03,
                  'gs-netw-msg3-' =>                  $list_03,
                  'gs-netw-msg4-' =>                  $list_03,
                  'gs-netw-msg5-' =>                  $list_03,
                  'gs-netw-msg6-' =>                  $list_03,
                  'gs-netw-msga-' =>                  $list_03,
                  'gs-netw-msgc-' =>                  $list_03,
                  'gs-netw-msgd-' =>                  $list_03,
                  'gs-netw-msge-' =>                  $list_03,
                  'ind stff-admin-adm-' =>            $list_04,
                  'ind stff-admin-apm-' =>            $list_04,
                  'ind stff-admin-fore-' =>           $list_04,
                  'ind stff-admin-lays-' =>           $list_04,
                  'ind stff-admin-mhan-' =>           $list_04,
                  'ind stff-admin-mman-' =>           $list_04,
                  'ind stff-admin-p6-' =>             $list_04,
                  'ind stff-admin-pe-' =>             $list_04,
                  'ind stff-admin-pm-' =>             $list_04,
                  'ind stff-admin-qa-' =>             $list_04,
                  'ind stff-admin-safm-' =>           $list_04,
                  'ind stff-admin-safp-' =>           $list_04,
                  'ind stff-admin-srpm-' =>           $list_04,
                  'ind stff-admin-stpm-' =>           $list_04,
                  'ind stff-admin-super-' =>          $list_04,
                  'safemeetwarmup-misc-smwu-' =>      [52],
                  'sche unproduc-misc-snpt-' =>       [55],
                  'train-misc-trne-' =>               [64],
                  'train-misc-trnh-' =>               [65],
                  'train-unbill-trne-' =>             [70],
                  'train-unbill-trnh-' =>             [72],
                  'travel-misc-trve-' =>              [66],
                  'travel-misc-trvh-' =>              [67],
                  'travel-unbill-trvh-' =>            [69],
                  'travel-unbill-trvl-' =>            [68],
                  'unsche unprod-misc-nsn-' =>        [73],
                  'ware-misc-whs-' =>                 [34],
            );
      
            foreach($tasktypes as $key=>$value){
                  $tasktypeID = DB::table('tasktypes')->insertGetId([
                        'name' => $key,
                        'description' => ''
                  ]);

                  $tasktype = Tasktype::findOrFail($tasktypeID);

                  // $subtasks = Subtask::all()
                  //       ->random(mt_rand(1,16))
                  //       ->pluck('id');

                  $subtasks = $value;

                  $tasktype->subtasks()->attach($subtasks);
            }
      }
}
